# Generated by Django 5.0.3 on 2024-06-10 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='HostLists',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('listing_name', models.CharField(max_length=125)),
                ('listing_address', models.CharField(max_length=250)),
                ('listing_price', models.IntegerField(max_length=100000)),
                ('listing_date', models.DateTimeField()),
                ('listing_picture1', models.ImageField(upload_to='listing_pics/')),
                ('listing_picture2', models.ImageField(upload_to='listing_pics/')),
                ('listing_picture3', models.ImageField(upload_to='listing_pics/')),
            ],
        ),
    ]
