# Generated by Django 5.0.3 on 2024-06-12 12:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0002_hostlists_listing_host_alter_hostlists_listing_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hostlists',
            name='listing_date',
        ),
    ]
