# Generated by Django 5.0.3 on 2024-06-23 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0003_remove_hostlists_listing_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hostlists',
            name='listing_picture1',
            field=models.ImageField(null=True, upload_to='listing_pics'),
        ),
        migrations.AlterField(
            model_name='hostlists',
            name='listing_picture2',
            field=models.ImageField(null=True, upload_to='listing_pics'),
        ),
        migrations.AlterField(
            model_name='hostlists',
            name='listing_picture3',
            field=models.ImageField(null=True, upload_to='listing_pics'),
        ),
    ]
