# Generated by Django 5.0.3 on 2024-06-27 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0004_alter_hostlists_listing_picture1_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='hostlists',
            name='listing_city',
            field=models.CharField(default='ahmedabad', max_length=100),
            preserve_default=False,
        ),
    ]
