# Generated by Django 5.0.3 on 2024-06-08 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hosts', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customhostuser',
            old_name='HostPic',
            new_name='Profile',
        ),
        migrations.AddField(
            model_name='customhostuser',
            name='City',
            field=models.CharField(default='', max_length=20),
        ),
    ]
