# Generated by Django 5.0.3 on 2024-06-08 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hosts', '0002_rename_hostpic_customhostuser_profile_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customhostuser',
            name='City',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='customhostuser',
            name='Profile',
            field=models.ImageField(default='', upload_to='pro_pics'),
        ),
    ]
