# Generated by Django 5.0.3 on 2024-06-08 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hosts', '0003_alter_customhostuser_city_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customhostuser',
            name='Profile',
            field=models.ImageField(blank=True, null=True, upload_to='pro_pics/'),
        ),
    ]
